# Generated by Django 4.2 on 2024-07-02 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_completed_at_testattempt_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='remained_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
