version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:alpine  # Using Redis alpine for a lightweight version
    container_name: redis-server
    ports:
      - "6379:6379"  # Expose Redis port
    restart: always

  web:
    build: .
    command: /usr/src/app/entrypoint.sh
    container_name: deepwater-web
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis  # Add redis as a dependency
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
